# Generated by Django 2.2.6 on 2019-10-18 18:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('ape_paterno', models.CharField(max_length=100)),
                ('ape_materno', models.CharField(max_length=100)),
                ('correo', models.EmailField(help_text='Introduzca su correo electrónico', max_length=200)),
                ('num_telefonico', models.IntegerField(max_length=9)),
            ],
            options={
                'ordering': ['primer_nombre', 'ape_paterno', 'ape_materno'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Ingresa la descripción del departamento', max_length=1000)),
                ('uf', models.IntegerField(max_length=10)),
                ('n_habitaciones', models.IntegerField(max_length=2)),
                ('n_banos', models.IntegerField(max_length=2)),
            ],
        ),
    ]
