# Generated by Django 2.2.6 on 2019-10-20 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['primer_nombre', 'apellido_paterno', 'apellido_materno']},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ape_materno',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='ape_paterno',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='n_banos',
            new_name='numero_banos',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='n_habitaciones',
            new_name='numero_habitaciones',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.Departamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='num_telefonico',
            field=models.CharField(max_length=9),
        ),
    ]
