# Generated by Django 2.2.6 on 2019-10-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_auto_20191020_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='numero_banos',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='numero_habitaciones',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='uf',
        ),
    ]
