# Generated by Django 2.2.6 on 2019-10-28 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_auto_20191020_0045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_materno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_paterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='primer_nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_completo',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
