# Generated by Django 2.2.6 on 2019-11-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_auto_20191027_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='numero_banos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamento',
            name='numero_habitaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departamento',
            name='uf',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id_departamento',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
